### ISSUE TITLE
Add cert creation date to route

### ISSUE THREAD

**Issue by tahonen** [ikke-t/cerbot-ocp#6]
Add annotation to route that describes when cert has been created and/or expire date.

**Comment by tahonen** [comment]
Something like this after route modified.

```  
/usr/bin/oc annotate "route/\${ROUTE}"  --overwrite \
letsencrypt-certificate-created=`date +"%Y-%m-%d-%H%M"
```

**Comment by ikke-t** [comment]
openssl x509 .... command gives you out the date
