### ISSUE TITLE
create an operator for certbot-ocp

### ISSUE THREAD

**Issue by ikke-t** [ikke-t/cerbot-ocp#7]
This was developed in OpenShift online, where one is not cluster-admin. But for such clusters where you are and admin, it sure would be nice to offer the service via an operator.

So create an operator, which set's up a kube cron job for cert renewal, and monitors for route creations and kicks this container to install certs when a new route is created or updated with proper label.

**Comment by tahonen** [comment]
There is already zillion operator based certificate tools. https://cert-manager.io/ maybe the most common. Current version of Openshift you need cluster admin to install operator. If you have cluster admin, you can use those other cert managers. Beaty of this project is that it can run in single namespace without cluster admin. Only namespace admin is needed.

**Comment by ikke-t** [comment]
OK, so let's stay in the original purpose
